commonLabels:
  object: mongodb

nodeSelector:
    node-role: worker

persistence:
  enabled: false

auth:
  rootPassword: "Weops#@$123"

volumePermissions:
  enabled: true

readinessProbe:
  enabled: false

livenessProbe:
  enabled: false

useStatefulSet: true

service:
  type: NodePort

resources:
  limits:
    cpu: 400m
    memory: 500Mi
